### ISSUE TITLE
Errors with python 3

### ISSUE THREAD

**Issue by sally-woolrich** [gjr80/weewx-polarwindplot#43] opened 2022-01-11 07:08 UTC
I tried this on bullseye with python 3.9.2 and WeeWx 4.5.1 and got the following error:

`Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine: Unable to instantiate generator 'user.polarWindPlot.PolarWindPlotGenerator'
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****  invalid syntax (polarWindPlot.py, line 261)
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 179, in run
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****      obj = weeutil.weeutil.get_object(generator)(
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1119, in get_o
bject
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****      mod = __import__(module)
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarWindPlot.py", line 261
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****      except IOError, e:
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****                    ^
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****  SyntaxError: invalid syntax
Jan 10 11:16:57 raspberrypi weewx[5736] ERROR weewx.reportengine:         ****  Generator ignored
`

I commented out that line and adjusted the indentation to get another error:

`Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine: Unable to instantiate generator 'user.polarWindPlot.PolarWindPlotGenerator'
Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine:         ****  cannot import name 'to_unicode' from 'weeutil.weeutil' (/home/weewx/bin/weeutil/weeutil.py)
Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 179, in run
Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine:         ****      obj = weeutil.weeutil.get_object(generator)(
Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1119, in get_object
Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine:         ****      mod = __import__(module)
Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarWindPlot.py", line 61, in <module>
Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine:         ****      from weeutil.weeutil import accumulateLeaves, option_as_list, TimeSpan, tobool, to_unicode
Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine:         ****  ImportError: cannot import name 'to_unicode' from 'weeutil.weeutil' (/home/weewx/bin/weeutil/weeutil.py)
Jan 10 13:27:04 raspberrypi weewx[6193] ERROR weewx.reportengine:         ****  Generator ignored
`
At that point I gave up!

**Comment by gjr80** [comment] 2022-01-12 22:02
Thanks. Definitely a python2/3 issue. I've started updating the polar wind plot code to be python 2/3 compatible but a couple of other things have come up. I hope to have the code to the stage where the current code runs under python 2/3 and WeeWX 4.0 or later by the end of the weekend.

**Comment by sally-woolrich** [comment] 2022-01-13 07:54
I noticed the comments on GitHub.  Was delighted you are moving on it so quickly!

If I was a Python programmer I’d have had a go at sorting it myself, but whilst I’ve done a lot of programming I’ve not done any in Python.

Look forward to trying the up-to-date version.

**Comment by gjr80** [comment] 2022-01-16 11:29
OK, should have a python2/3 compatible version now. Have also worked through quite a few other issues, some that were identified a few years go and a number found in the last few days. I haven't packaged things up into an extension package yet, but since you already have the code installed the easiest approach I think is just for you to download the `polarwindplot.py` file  and save it in place of your existing copy.

To download `polarwindplot.py` just use:
```
$ wget https://raw.githubusercontent.com/gjr80/weewx-polarwindplot/master/bin/user/polarwindplot.py
```
and copy `polarwindplot.py` to `/home/weewx/bin/user`. You might notice that the file name has changed from `polarWindPlot.py` to `polarwindplot.py`, unfortunately this means you will need to make a change to `skin.conf` for any skins where you are using the Polar Wind Plot generator. You will need to change the following line:
```
# The list of generators that are to be run:
[Generators]
    generator_list = user.polarWindPlot.PolarWindPlotGenerator
```
to
```
# The list of generators that are to be run:
[Generators]
    generator_list = user.polarwindplot.PolarWindPlotGenerator
```
I haven't changed any of the generator config items that you might use in `skin.conf`; however, in fixing a few issues I may have caused some behaviour changes that might affect the generated plots. So if you notice anything odd/different in the output please let me know.

And of course if the new generator doesn't work or throws errors in the log please post a copy of the log trace.

**Comment by sally-woolrich** [comment] 2022-01-16 15:28
Wonderful!  I’ll have a go tomorrow and let you know.

Was only using two of the plots so if there are issues with others I won’t find them

**Comment by sally-woolrich** [comment] 2022-01-17 12:27
It is fine in Python 3, but whilst the rose graphic is fine, the spiral one is nothing like it used to be:

[https://pilots.scottishglidingcentre.co.uk/_media/weather/windrose/dot4spiral.png]

[http://192.168.1.150/weather/sgc/windrose/dayspiral.png]

**Comment by gjr80** [comment] 2022-01-17 14:19
I cannot open one if the plots. I can open dots4spiral.png but cannot open dayspiral.png, looks like the address is a private network ip address.

**Comment by sally-woolrich** [comment] 2022-01-17 14:21
Ah sorry about that, must have copied the link not the image.  Is this better?

[http://192.168.1.150/weather/sgc/windrose/dayspiral.png]

**Comment by gjr80** [comment] 2022-01-17 19:43
Ah, no, it's still the same 192.168.1.150 address.

**Comment by sally-woolrich** [comment] 2022-01-18 08:58
Oh drat.

This shows the scatter as well, though I don’t use it.

***@***.***

**Comment by sally-woolrich** [comment] 2022-01-18 16:41
BTW this is using the same data (via the GW1000 driver) as my live station, though I’ve not put these plots on it:

https://muchty-weather.org.uk/weather/

**Comment by gjr80** [comment] 2022-01-18 20:03
Thanks but so far I've only seen one plot and I'm not sure if that is the old one (which I presume you want) or the new one that you said is different (I presume you don't want).

Did you see my amended comment from yesterday?

**Comment by sally-woolrich** [comment] 2022-01-19 08:45
This lead me to believe you had the example of what it is currently – dots4spiral.png is from the live site:

https://pilots.scottishglidingcentre.co.uk/weather/weather_station

***@***.***

Not sure I’ve seen the comments you mentioned.  Were they in email (I can’t find one) or at GitHub?

**Comment by gjr80** [comment] 2022-01-19 08:57
Yes I have dot4spiral.png but not the other. Without seeing the other it's a bit hard to know what to fix. It may simply be a setting that needs to be changed or it could be a bug. 

I edited my comment on GitHub a couple of days back. Not sure how GitHub email works (I use the GitHub app or access via browser) but I guess it's possible you were only emailed my original comment and not the updated comment.

**Comment by sally-woolrich** [comment] 2022-01-19 09:44
OK I’ve not had an email from GitHub although it looks like I have notifications on, but I looked and see you’ve changed a font and the background colour.

This image should show the output on my system for each type of plot for a day.

![image](https://user-images.githubusercontent.com/43567521/150105104-39d46ef1-a1c9-4b34-870c-8ef4c25ec06e.png)

**Comment by gjr80** [comment] 2022-01-19 12:26
Thanks. Can see those four plots.

Considering the spiral plot. `dot4spiral.png` is dots only and the 18/1 04:20 spiral plot is lines only. Assuming you want dots and not lines then try the following settings in `skin.conf` (assuming here the plot name dot4spiral is the `[[ ]]` stanza):
```
[PolarWindPlotGenerator]
    ....
    [[dot4spiral]]
        line_type = none
        marker_type = dot
        ....
````
This will turn on dots and turn off the lines. I made a change to the logic in how these two setting are processed, previously it was to easy to end up with a plot with no dots or lines (ie nothing) and the settings for turning off dots or lines were not intuitive. I guess this means the new version broke what previously worked.

Regards background colour. The old code used the config setting `image_background_box_color` to set the background colour for the rectangular box containing the plot. I don't know why I chose that name, I simplified it to follow the WeeWX image generator convention and renamed it to `image_background_color`. I'm guessing your old setting is now being ignored and you are getting the default light blue. Sorry, should have mentioned that. All you need do in `skin.conf` is change `image_background_box_color` to `image_background_color` for each affected plot.

I didn't change the underlying font family, that is still set by `font_path` in `skin.conf` (if `font_path` is not set then you get a default font from the python imaging library). I did make a change to the font format used for the 'spiral direction label' (ie the label that says 'Oldest (04:25) in center`) as it was using the legend font format (ie the font format used on the legend labelling) and I changed it to the label font format (ie the format format used for the plot title and timestamp). Now that I look at them again it is probably appropriate for the plot title to stay as is and all other labels should use the (default) smaller legend font format. What do you think?

**Comment by sally-woolrich** [comment] 2022-01-19 13:34
OK got dots but the default size of 1 is tiny!

***@***.***

I’ve increased it to 4:

***@***.***

This is without your latest change

**Comment by sally-woolrich** [comment] 2022-01-21 16:24
Something untoward is going on.  If you look at the times on the plots, only the wind rose is correct at 16:00.  I replaced the .py with the latest one from GitHub and got these error messages.  I’ve not changed skin.conf since the 19th, when I put in marker_type and marker_size.  The first error was on the 18th at 04:27.  I didn’t find any in syslog.1, and syslog goes back to Jan 16.

This is the latest set, from well after I copied the new .py in and restarted WeeWx:

Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.polarwindplot.PolarWindPlotGenerator'
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****  unsupported operand type(s) for //: 'NoneType' and 'int'
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 196, in run
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****      obj.start()
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 281, in start
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****      self.run()
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 170, in run
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****      self.genPlots(self.gen_ts)
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 289, in genPlots
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****      image = plot_obj.render(title)
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 1462, in render
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****      self.set_plot()
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 1498, in set_plot
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****      quadrant_count[int(_dir_vec // 90)] += 1
Jan 21 16:07:15 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****  TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
Jan 21 16:07:16 raspberrypi weewx[28526] ERROR weewx.reportengine:         ****  Generator terminated


***@***.***

**Comment by gjr80** [comment] 2022-01-21 22:49
When you say '_If you look at the times on the plots, only the wind rose is correct at 16:00_' I presume you mean the wind rose plot is current but the remaining plots are not, ie they were last generated some time ago. This is most likely the result of the error trace you provided, it indicates an error in the scatter plot. When a WeeWX generator encounters a fatal error such as this the generator aborts and any remaining plots are skipped. I'm guessing `skin.conf` has the wind rose plot first then the scatter plot and then the others. In this case the wind rose generates fine, the scatter throws the error so it is not generated, the generator aborts and the trail and spiral plots are skipped.

Let me work through the scatter plot issue. I thought any changes I made were benign but perhaps that is not the case, or perhaps it is something else.

**Comment by gjr80** [comment] 2022-01-21 23:11
OK. Unusual error, easy enough to fix but I am unsure why it has not reared it's head before.

Please download and install the latest `polarwindplot.py`. I've made this version `0.1.0b2`.

**Comment by sally-woolrich** [comment] 2022-01-22 08:21
My weather station is very sheltered from the wind so has plenty of ‘None’ for the direction – I believe some stations use ‘N’ instead.  So it’s unusual!  I’m only using it as a testbed as the day will come when I move the one at the gliding club to bullseye & python 3.

Gaugeengine has a similar problem but continues to produce output.

However I have a new error.  Again the rose is produced but not the other plots…


Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.polarwindplot.PolarWindPlotGenerator'
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****  unsupported operand type(s) for //: 'NoneType' and 'int'
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 196, in run
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****      obj.start()
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 281, in start
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****      self.run()
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 170, in run
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****      self.genPlots(self.gen_ts)
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 289, in genPlots
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****      image = plot_obj.render(title)
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 1462, in render
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****      self.set_plot()
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 1498, in set_plot
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****      quadrant_count[int(_dir_vec // 90)] += 1
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****  TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
Jan 22 08:16:55 raspberrypi weewx[30111] ERROR weewx.reportengine:         ****  Generator terminated

**Comment by gjr80** [comment] 2022-01-22 08:42
That's the same error as you reported previously. Did you download the updated `polarwindplot.py` and replace your existing `polarwindplot.py`? WeeWX appears to still be using the old file as the error trace you posted reports line 1498 is 
```
quadrant_count[int(_dir_vec // 90)] += 1
```
In the updated file that line is now line 1500.

Did you restart WeeWX after downloading the updated file? If you update a `.py` file you need to restart WeeWX.

**Comment by sally-woolrich** [comment] 2022-01-22 09:03
I’ll double-check & get back to you

**Comment by sally-woolrich** [comment] 2022-01-22 09:22
Ah got myself confused with the change of case in the file name.  I had stopped & restarted WeeWx.  And I did it on the laptop with ‘assistance’ from the cats!

It’s OK now for the rose & spiral.  Not sure how useful the scatter would be!

***@***.***

**Comment by gjr80** [comment] 2022-01-22 10:56
Ah, good that it is running error free. I can't say I've ever seen a cat that is too good around computers. 

I just prefer the traditional wind rose. I put together a WeeWX generator that just produced a wind rose for my web site some 8-9 years ago. A few years later another WeeWX user approached me about producing other polar plots and we started working together on this project. I must admit it was my partner in crime that came up with the other three plot types. A while later he moved on to a new job that left him no time for WeeWX and not long after this project stagnated. 

I think the spiral plot is somewhat similar to the spiral wind plot produced by WeatherDisplay but the others are somewhat unique.

If you are interested I have started documenting the different options supported by the polar wind plot generator.  I have included all of the options that are common to all plots, I just have to add those that are specific to each plot type. I aim to have those done over the next couple of days. You will find them on the [options wiki page](https://github.com/gjr80/weewx-polarwindplot/wiki/Available-Config-Options).

**Comment by sally-woolrich** [comment] 2022-01-22 15:28
Hi

Yes, cats & computers don’t really mix.  Neither does the laptop and anything serious!

Yes, I’m interested in the documentation and I’ll keep an eye on the Wiki.

The previous weather station software had the spiral and I find it’s good for showing the trends of directional & strength change.  Glider pilots are compulsive about the weather!

Thanks

**Comment by sally-woolrich** [comment] 2022-01-26 11:26
I’ve copied the latest version over, I’m sure it will be OK having looked at the changes.

**Comment by sally-woolrich** [comment] 2022-01-26 11:32
I spoke to soon.  I've copied b2 back.

Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.polarwindplot.PolarWindPlotGenerator'
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****  'PolarWindScatterPlot' object has no attribute 'bullseye'
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 196, in run
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****      obj.start()
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 281, in start
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****      self.run()
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 171, in run
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****      self.genPlots(self.gen_ts)
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 290, in genPlots
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****      image = plot_obj.render(title)
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 1468, in render
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****      self.render_polar_grid()
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 782, in render_polar_grid
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****      ring_space = (1 - self.bullseye) * self.max_plot_dia/(2.0 * self.rings)
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****  AttributeError: 'PolarWindScatterPlot' object has no attribute 'bullseye'
Jan 26 11:28:36 raspberrypi weewx[5185] ERROR weewx.reportengine:         ****  Generator terminated

--
Sally Woolrich
Mobile: 07793 452788
Home: 01337 328907

**Comment by sally-woolrich** [comment] 2022-01-26 11:35
On comparing b2 & b3:

    def render_polar_grid(self, bullseye=0):                                  |     def render_polar_grid(self):

I've left b2 in place.

--
Sally Woolrich
Mobile: 07793 452788
Home: 01337 328907

**Comment by gjr80** [comment] 2022-01-26 11:45
Sorry, silly mistake on my behalf. Try b4.

**Comment by sally-woolrich** [comment] 2022-01-26 11:53
That’s fixed it.

***@***.***

**Comment by sally-woolrich** [comment] 2022-01-29 10:14
Quick question, I believe this works with Python 2 as well.  Correct?

Looked at the commits, there are a lot of them!

**Comment by gjr80** [comment] 2022-01-29 10:17
Should work under python2 but I can't guarantee it as I only tested under python3.

**Comment by sally-woolrich** [comment] 2022-01-29 13:37
When I get a chance I’ll let you know.

**Comment by gjr80** [comment] 2022-06-16 05:28
Python 2 and 3 operation confirmed. Closing as [v0.1.0](https://github.com/gjr80/weewx-polarwindplot/releases) has been released.

**Closed by gjr80** 2022-06-16 05:28 UTC
